services:
  backend:
    container_name: back-end-v2.0
    image: product-back-end
    build: ./Back-End/
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  frontend:
    container_name: front-end-v2.0
    image: product-front-end
    build: ./Front-End/emstore-update/
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
      - backend

  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=productstore